# The basics
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export EDITOR=nvim

export ZSH_CACHE_DIR="$HOME/.cache"

# Plugins
source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh
antidote load

# Load external config config
source $HOME/code/vinibaggio-dotfiles/zsh/aliases
source $HOME/code/vinibaggio-private/zsh/zshrc

# Load my own scripts
export PATH="$PATH:$HOME/code/vinibaggio-dotfiles/bin"

# If 1password agent file is present, set it as the ssh-agent
if [ -e $HOME/.1password/agent.sock ]; then
	export SSH_AUTH_SOCK=$HOME/.1password/agent.sock
fi

# bun completions
[ -s "/Users/vinibaggio/.bun/_bun" ] && source "/Users/vinibaggio/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
